### ISSUE TITLE
README and help message out of sync

### ISSUE THREAD

**Issue by bartekpacia** [knei-knurow/lidar-visualizations#31]
The options in the README and program help menu are different – e.g `--gui` is only listed in README (but it indeed exists and works)

README:
<img width="982" alt="Screenshot 2020-12-26 at 01 45 57" src="https://user-images.githubusercontent.com/40357511/103143700-1f04d980-471c-11eb-9fea-bfd4448ba99e.png">

help message:
![Screenshot 2020-12-26 at 01 47 24](https://user-images.githubusercontent.com/40357511/103143707-55425900-471c-11eb-8ace-049fc1450c9c.png)

**Comment by dsonyy** [comment]
Good point, I'll take care of it soon.

**Comment by bartekpacia** [comment]
you could also add displaying "help message" when there aren't any arguments passed
