### ISSUE TITLE
Display help by default

### ISSUE THREAD

**Issue by bartekpacia** [knei-knurow/lidar-visualizations#8]
I think the following behavior (i.e when no options/flags are passed) is a bit confusing:

<img width="662" alt="screen" src="https://user-images.githubusercontent.com/40357511/102027366-c80a1680-3da3-11eb-87f1-5f66bd8ed042.png">

I'd suggest displaying help when no options/flags are passed.

**Comment by dsonyy** [comment]
The default GUI is the SFML one. You probably have built the project without it, so it's unable to find the GUI with the default id.

**Comment by bartekpacia** [comment]
makes sense

what about adding short information, like "if you wanted to use the GUI mode, make sure that you linked SFML"?

**Comment by dsonyy** [comment]
I would suggest to set the terminal gui as the default one if SFML is not linked.
